---
layout: post
title:  "리팩토링 위키"
author: "glqdlt"
---


# 분류 코드에 따른 분기를 객체지향적으로

게임 회사에 재직할 떄의 이야기이다. 게임에는 많은 재화가 존재한다. 예를 들어 우리 일상생활의 돈이라는 개념이 게임에서는 게임 돈(게임머니), 현금 캐시 돈(크리스탈), 보너스 포인트 등으로 너무나도 무궁무진하게 많다. 이런 많은 재화들을 소스상에서 구별하기 위해서 일반적으로 각 게임 재화별로 특별한 인덱스 값(대부분 정수형) 부여하는 식으로 많이들 작업을 할터이다. 입사 당시 운영자가 유저의 게임재화를 선물 할 수 있는 코드는 아래의 모습이었다.

```java
    public void charge(int moneyType){

        ...

        switch(moneyType){
//            게임머니
            case 0:
                ...
                break;
//            게임 보너스 코인   
            case 1:
                ...
                break;
//            유저 결제 수정    
            case 2:
                ...
                break;
            ....
        }
        ...

    }

```

위 코드에서 switch 문에 대해서는 문제가 없다. 큰 문제는 0,1,2 가 무엇을 뜻하는 지를 주석을 보거나 옆 사람에게 물어보지 않는 이상은 명확하게 파악할 수가 없다.

이를 개선해서 아래의 코드같이 만들어보자.

```java
    public void charge(int moneyType) {

        final int GAME_MONEY = 0;
        final int GAME_COIN = 1;
        final int CRYSTAL = 2;

        if (moneyType == GAME_MONEY) {
            ...
        } else if (moneyType == GAME_COIN) {
            ...
        } else if (moneyType == CRYSTAL) {
            ...
        } else {
            throw new RuntimeException(String.format("Not Supported MonetType, '%s'", moneyType));
        }

    }
```


# 메소드 간의 커뮤니케이션을 객체지향적으로

일반적으로 개발 문화가 성숙하지 못한 곳에서는 아래와 같은 코드를 쉽게 볼 수 있다.

```java


    public CommonResult someMethod(){
        ...
        CommonResult commonResult = new CommonResult();

        if(...){
            commonResult.setResult(true);
            commonResult.setMessage("성공");
        }else{
            commonResult.setResult(false);
            commonResult.setMessage("Null 입니다.");
        }
        return commonResult;
    }

```

이 상태의 문제점은 호출하는 상위 메소드에서도 계속 CommonResult 를 사용하게끔 구속하는 문제가 발생하고, 주구장창 CommonResult 상태를 확인해서 성공인지 실패인지를 체크하는 DRY 패턴이 나타나게 된다.

더 놀라운 것은 메소드의 return 이 void 여야만 할 메소드 조차, 결과 객체를 반환하게 된다는 우스꽝스러운 모습도 발생한다. 

예를 들면 아래처럼 단순히 콘솔에 데이터를 출력하는 메소드를 보라.
```java
    public CommonResult echo(String message){
        
        CommonResult commonResult = new CommonResult();

        if(message == null){
            commonResult.setResult(false);
            commonResult.setMessage("Null 입니다.");
        }else{
            System.Out.Println(message);
            commonResult.setResult(true);
            commonResult.setMessage("성공");
        }
        return commonResult;
    }

```

사실 void 메소드의 경우, 우리 모두다 사용해봐서 익숙히 잘 아는 부분이 있다. 성공을 하면 무소식이 희소식인 것 처럼 고요할 것이고, 실패한 경우에는 에러가 발생해서 실패 여부를 확인 할 수 있다.

아래처럼 고쳐볼 수 있다. 훨씬 간결하고 명확하지 않은가?
```java
    public void echo(String message){

        if(message == null)){
            throw new MessageNullException("메세지의 값을 할당해주세요.");
        }
        System.Out.Println(message);
    }
```

 즉, 메소드 간의 커뮤니케이션은 에러를 통해 성숙한 커뮤니케이션을 충분히 할 수 있다. 응답 값이 있는 경우도 보자.

```java
    public int plus(int a, int b){
        if(a < 0 || b < 0){
            throw new IllegalArgsException("값이 0 보다 작습니다.");
        }
    
        return a+b;
    }
```

에러를 다루어서 커뮤니케이션할 떄에는 메소드 응답에 대한 자유로운 커뮤니케이션이라는 장점도 있지만, 하나의 큰 에러를 두고 이를 확장하는 sub exception 들을 구현하여 에러 헨들링을 유기적으로 할 수가 있다.

예를 들면 아래와 같은 계층의 에러들이 존재한다고 보자.

```java
- RuntimeException
    ㄴ MyException
        ㄴ MySubExceptionA
        ㄴ MySubExceptionB
        ㄴ MySubExceptionC
    ㄴ SpringFrameworkException
        ㄴ ..
        ㄴ ..
    ㄴ DatabaseException
        ㄴ ..
        ㄴ ..
    ㄴ IllegalArgsException
        ...
```
MyException 은 특정한 상황의 에러가 나타냈음을 표현하는 에러이고, 실제 어떠한 상황인지를 특정지어주는 MySubExceptionA,B,C 의 하위 에러들을 가지는 구조이다.  만약 어떠한 기능 메소드에서 특정 기능 실패 시에 MySubExceptionA 또는 B를 throw 하는 메소드가 있다면, 이 메소드를 호출하는 상위 메소드에서는 MyException 만을 catch 해서 내가 작성한 예상이 되는(알고 있는, 또는 관리할 수 있는) 에러와 예상하지 못한 에러를 구분해서 헨들링할 수도 있어진다.
```java
    public void someMethod(){

        try{
            ...
        }catch(MyException){
            // 내가 예상하는 에러 제어
        }catch(SprnigFrameworkException){
            // 프레임워크에서 발생한 에러 제어
        }catch(DatabaseException){
            // 데이터베이스에서 발생한 에러 제어
        }

    }
```

자바의 비검사 예외인 RuntimException 을 확장(상속) 해서 사용하는 경우에 대한 이야기. (비검사 예외에는 컴파일러 입장에서 '비검사' 한다는 의미이다. 반대로는 검사 예외 Exception 이 있다.)

RuntimeException 을 일반적으로 사용하는 추세(자바 진영에서도 추천) 하는 이지만, 제임스 고슬링이 왜이렇게 설계했는 지에 대해서는 잠시 생각을 해볼 필요가 있다.


java.util.Iterator.next() 는 다음 엘리먼트가 있다면 값을 꺼내고 포인트를 움직이는 메소드이다. 만약 존재하지 않는다면  NoSuchElementException 을 throw 한다.

NoSuchElementException 는 RuntimeException을 상속받는 에러로서, '비검사 예외' 이다.

비검사 예외에는 컴파일 시점에서 예외에 대한 핸들링에 대해 확인하지 않는다. 반면, 검사 예외라면 try ~ catch 로 호출자가 핸들링을 하게하거나, 상위 호출자에게 위임하는 메소드 정의 시에 throws 절을 작성해야 한다.

Iterator.next() 의 경우를 다시 마저 말을 하면, 정상적으로 값을 읽으면서 결국은 에러를 반환하면 끝났음을 확인해야하는 걸까라고 생각할 수 있다. 이렇다면 에러를 만나기 위해 호출하는 꼴이기 때문에 모양새가 굉장히 웃기는 상황이 되어버린다. 이를 막고자 일반적으로 다음에 값이 존재하는 지를 확인시켜주는 hasNext() 라는 메소드가 존재한다. 이런 메서드를 사전 확인용 메서드(유키히로시, 자바로 배우는 리팩토링 입문)라고 표현하는 데, 비검사 예외를 작성할 경우에는 이처럼 사전 확인용 메서드를 제공해주는 것을 고민해볼 필요가 있다.

위를 고려해보면 조금 억지스럽지만 plus() 메소드에도 사전 확인용 메소드를 제공해볼 수도 있다.
```java

    public boolean isPlusMethodSupported(int value){
        return 0 <= value;
    }

    public int plus(int a, int b){
        if(a < 0 || b < 0){
            throw new IllegalArgsException("값이 0 보다 작습니다.");
        }
    
        return a+b;
    }
```
